## Huggingface model
## @section Model
## ref: https://huggingface.co/models
## @param model.organization Models' company name on huggingface, required!
## @param model.name Models' name on huggingface, required!
## e.g. to deploy model https://huggingface.co/segmind/SSD-1B use configuration below:
## organization: segmind
## name: SSD-1B
##
model:
  organization: ""
  name: ""

## Init configuration. By default, init clone model from huggingface git.
## The another way is to upload model to s3 bucket to reduce init delay and external traffic.
## @param init.s3.enabled Turn on/off s3 data source Default: disabled
## @param init.s3.bucketURL Full s3 URL included path to model's folder
##
init:
  s3:
    enabled: false
    bucketURL: s3://k8s-model-zephyr/llm/deployment/segmind/SSD-1B

## huggingface block configure running text-generation-launcher internal port and additional arguments
## @param huggingface.containerPort Deployment/StatefulSet ContainerPort, optional
##
huggingface:
  containerPort: 8080
  ## @param huggingface.args Additional arg for text-generation-launcher optional
  ## e.g.
  ##  args:
  ##   - "--quantize"
  ##   - "bitsandbytes"
  ##   - "--num-shard"
  ##   - "1"
  ##
  args: []

## @section Global
## @param replicaCount Deployment/StatefulSet replicaCount
##
replicaCount: 1

## @param kind Resource king [allowed values: deployment/StatefulSet, optional]
##
kind: deployment

## Huggingface image
## @param image.repo Huggingface image repo
## @param image.tag Huggingface image version
## @param image.pullPolicy Huggingface image pull policy
## ref: https://kubernetes.io/docs/concepts/containers/images/#image-pull-policy
##
image:
  repo: ghcr.io/huggingface/text-generation-inference
  tag: "latest"
  pullPolicy: IfNotPresent

## @param imagePullSecrets May need if used private repo as a cache for image ghcr.io/huggingface/text-generation-inference
#
imagePullSecrets: []

## @param nameOverride String to partially override common.names.name
##
nameOverride: ""

## @param fullnameOverride String to fully override common.names.fullname
##
fullnameOverride: ""

## Persistence parameters
## ref: https://kubernetes.io/docs/concepts/storage/persistent-volumes/
## @param persistence.accessModes PVC accessModes
## @param persistence.storageClassName Kubernetes storageClass name
## @param persistence.storage Volume size
##
persistence:
  accessModes:
  - ReadWriteOnce
  storageClassName: gp2
  storage: 100Gi

## Persistence parameters
## ref: https://kubernetes.io/docs/concepts/services-networking/
## @param service.port Service port, default 8080
## @param service.type Service type, default ClusterIP
##
service:
  port: 8080
  type: "ClusterIP"

## ServiceAccount parameters
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
## @param serviceAccount.create Enable/disable service account, default enabled
## @param serviceAccount.role Kubernetes role configuration, default nil
##
serviceAccount:
  create: true
  role: {}
#     rules:
#     - apiGroups:
#         - ""
#       resources:
#         - endpoints
#         - pods
#         - nodes
#         - services
#       verbs:
#         - get
#         - list

## @param podAnnotations Annotations for Redis&reg; replicas pods
## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
##
podAnnotations: {}

## Configure Pods Security Context
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
## @param securityContext Set pod's Security Context fsGroup
##
securityContext: {}
#   capabilities:
#     drop:
#     - ALL
#   readOnlyRootFilesystem: true
#   runAsNonRoot: true
#   runAsUser: 1000

## @param extraEnvVars Array with extra environment variables to add to main pod
## e.g:
## extraEnvVars:
##   - name: FOO
##     value: "bar"
##
extraEnvVars: []

## Configure the ingresses resources list that allows you to access the model API
## @param ingresses.enabled Enable/disable ingress(es) for model API, default disabled
##
ingresses:
  enabled: false
  ## ingresses list
  ## ref: https://kubernetes.io/docs/concepts/services-networking/ingress/
  ## @param ingresses.configs List of ingresses configs
  ## e.g.
  ## configs:
  ## - annotations:
  ##     cert-manager.io/cluster-issuer: "letsencrypt-http"
  ##   hosts:
  ##     - host: api.model.example.com
  ##       paths:
  ##         - path: /
  ##           pathType: Prefix
  ##   tls:
  ##     - hosts:
  ##         - api.model.example.com
  ##       secretName: huggingface-model
  ##
  configs: []


## @param livenessProbe Configure extra options for model liveness probe
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#configure-probes
##
livenessProbe: {}
#   failureThreshold: 4
#   httpGet:
#     path: /
#   initialDelaySeconds: 1
#   periodSeconds: 5
#   successThreshold: 1
#   timeoutSeconds: 3

## @param readinessProbe Configure extra options for model readiness probe
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#configure-probes
##
readinessProbe: {}
#   failureThreshold: 3
#   httpGet:
#     path: /
#   initialDelaySeconds: 1
#   periodSeconds: 3
#   successThreshold: 2
#   timeoutSeconds: 2

## @param startupProbe Configure extra options for model startup probe
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#configure-probes
##
startupProbe: {}
#   failureThreshold: 10
#   httpGet:
#     path: /
#   initialDelaySeconds: 15
#   periodSeconds: 5
#   successThreshold: 1
#   timeoutSeconds: 3

## PodDisruptionBudget configuration
pdb:
  ## @param pdb.create Specifies whether a PodDisruptionBudget should be created
  ##
  create: false
  ## @param pdb.minAvailable Min number of pods that must still be available after the eviction
  ##
  minAvailable: 1
  ## @param pdb.maxUnavailable Max number of pods that can be unavailable after the eviction
  ##
  maxUnavailable: ""

## Init container's resource requests and limits
## ref: https://kubernetes.io/docs/user-guide/compute-resources/
## @param resources.limits.nvidia.com/gpu The required option by text-generation-launcher
## @param resources.requests.cpu The requested CPU minimal recommended value
## @param resources.requests.memory The requested memory minimal recommended size
##
resources:
  requests:
    cpu: "3"
    memory: "10Gi"
  limits:
    nvidia.com/gpu: 1

## @param extraVolumes Optionally specify extra list of additional volumes for models' pods
## e.g.
##   - hostPath:
##       path: /opt/model/logs
##       type: DirectoryOrCreate
##     name: logging
##
extraVolumes: []

## @param extraVolumeMounts Optionally specify extra list of additional volumeMounts for models' container
## e.g.
##   - mountPath: /opt/model/logs
##     name: logging
##
extraVolumeMounts: []

## Model Autoscaling configuration
## ref: https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/
## @param autoscaling.enabled Enable Horizontal POD autoscaling for model
## @param autoscaling.minReplicas Minimum number of model replicas
## @param autoscaling.maxReplicas Maximum number of model replicas
## @param autoscaling.targetCPU Target CPU utilization percentage
## @param autoscaling.targetMemory Target Memory utilization percentage
##
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPU: 50
  targetMemory: 50

## @param affinity Affinity for pod assignment
## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
## NOTE: podAffinityPreset, podAntiAffinityPreset, and nodeAffinityPreset will be ignored when it's set
##
affinity: {}
## @param nodeSelector Node labels for pod assignment
## ref: https://kubernetes.io/docs/user-guide/node-selection/
##
nodeSelector: {}
## @param tolerations Tolerations for pod assignment
## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
##
tolerations: []

